/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { findAllReviewsByBook } from '../fn/reviews/find-all-reviews-by-book';
import { FindAllReviewsByBook$Params } from '../fn/reviews/find-all-reviews-by-book';
import { PageResponseReviewResponse } from '../models/page-response-review-response';
import { saveReview } from '../fn/reviews/save-review';
import { SaveReview$Params } from '../fn/reviews/save-review';

@Injectable({ providedIn: 'root' })
export class ReviewsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveReview()` */
  static readonly SaveReviewPath = '/reviews';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveReview()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveReview$Response(params: SaveReview$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveReview(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveReview$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveReview(params: SaveReview$Params, context?: HttpContext): Observable<number> {
    return this.saveReview$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findAllReviewsByBook()` */
  static readonly FindAllReviewsByBookPath = '/reviews/book/{bookId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllReviewsByBook()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllReviewsByBook$Response(params: FindAllReviewsByBook$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseReviewResponse>> {
    return findAllReviewsByBook(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllReviewsByBook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllReviewsByBook(params: FindAllReviewsByBook$Params, context?: HttpContext): Observable<PageResponseReviewResponse> {
    return this.findAllReviewsByBook$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseReviewResponse>): PageResponseReviewResponse => r.body)
    );
  }

}
